server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 3
    eureka-server-connect-timeout-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 30

spring:
  profiles:
    active: local

  application:
    name: payment-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payments
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    
topic:
  payment-topic: payment-topic
  order-topic: order-topic